[versions]
kotlin = "2.4.20"
agp = "9.4.1"
composeBom = "2026.09.00"
activityCompose = "1.13.0"

[libraries]
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui = { module = "androidx.compose.ui:ui" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
